In [1]:
import pandas as pd

In [2]:
yn = pd.read_csv('../data/yo_nunca.csv', index_col='index')
yn

                                                  frases
index
1                Yo nunca lo he hecho sin haber querido.
2       Yo nunca lo he hecho con mas de una persona e...
3       Yo nunca he querido tirarme a la madre/padre ...
4       Yo nunca he querido tirarme al hermano/a de u...
5       Yo nunca me he querido liar con alguien presente
...                                                  ...
347     Yo nunca me he liado/tirado o tenido algo con...
348     A mi nunca me ha tirado la caña un familiar d...
349     Yo nunca he pensado que por ejemplo (persona ...
350                Yo nunca he mentido en este Yo Nunca.
351     Yo nunca me he limpiado el culo tan fuerte qu...

[351 rows x 1 columns]

In [3]:
yn.to_csv('../data/yo_nunca.csv', index=False)

In [4]:
yn.columns

Index(['frases'], dtype='str')

In [6]:
cosmo = pd.read_csv("../data/raw/cosmo.csv", names=['frases'])
esquire = pd.read_csv("../data/raw/esquire.csv", names=['frases'])
toz = pd.read_csv("../data/raw/toz.csv", names=['frases'])
pyn = pd.read_csv("../data/raw/pyn.csv", names=['frases'])
uncomo = pd.read_csv("../data/raw/uncomo.csv", names=['frases'])

In [7]:
full_yn =pd.concat([yn,cosmo,esquire,toz,pyn,uncomo], ignore_index=True)

In [ ]:
full_yn

In [ ]:
cosmo.shape

In [ ]:
print(type(yn))
print(type(cosmo))
print(yn.shape, cosmo.shape)
print(yn.columns if hasattr(yn, "columns") else yn.name)
print(cosmo.columns if hasattr(cosmo, "columns") else cosmo.name)

In [ ]:
full_yn.to_csv('../data/full_yo_nunca.csv', index=False)

In [ ]:
pd.read_csv('../data/full_yo_nunca.csv')

In [8]:
pd.read_csv('../data/full_yo_nunca_limpio.csv')

                                                 frases
0               Yo nunca lo he hecho sin haber querido.
1      Yo nunca lo he hecho con mas de una persona e...
2      Yo nunca he querido tirarme a la madre/padre ...
3      Yo nunca he querido tirarme al hermano/a de u...
4      Yo nunca me he querido liar con alguien presente
...                                                 ...
1124                   Yo nunca he tomado afrodisíacos.
1125  Yo nunca me he liado con alguien sin saber su ...
1126             Yo nunca he tenido un fetiche extraño.
1127        Yo nunca me he grabado teniendo relaciones.
1128  Yo nunca me he liado con un estudiante de inte...

[1129 rows x 1 columns]